name: PR Title Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const title = context.payload.pull_request.title;
            const conventionalRegex = /^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .{1,50}/;
            if (!conventionalRegex.test(title)) {
              core.setFailed(
                `El título del PR debe usar Conventional Commits, ejemplo: "feat(login): agregar autenticación"`
              );
            }
